+---------------------------+------------------+
| Field                     | Value            |
+---------------------------+------------------+
| first_name                | abhishek         |
| last_name                 | kamble           |
| username                  |                  |
| emplyeeIdentficationCode  | 0                |
| email                     | abhishek@marolix.com |
| password                  |                  |
| designation               | des1             |
| department                | Technology       |
| phone                     | 7008038842       |
| joining_date              | 2023-10-03       |
| isAdmin                   | False            |
| salary                    | 60500.00         |
| currency                  | INR              |
| casual_leave_days         | 20               |
| medical_leave_days        | 20               |
| lop_leave_days            | 0                |
| can_read_holidays         | True             |
| can_write_holidays        | True             |
| can_create_holidays       | True             |
| can_delete_holidays       | True             |
| can_import_holidays       | True             |
| can_export_holidays       | True             |
| can_read_leaves           | True             |
| can_write_leaves          | True             |
| can_create_leaves         | True             |
| can_delete_leaves         | True             |
| can_import_leaves         | True             |
| can_export_leaves         | True             |
| can_read_clients          | True             |
| can_write_clients         | True             |
| can_create_clients        | True             |
| can_delete_clients        | True             |
| can_import_clients        | True             |
| can_export_clients        | True             |
| can_read_projects         | True             |
| can_write_projects        | True             |
| can_create_projects       | True             |
| can_delete_projects       | True             |
| can_import_projects       | True             |
| can_export_projects       | True             |
| can_read_tasks            | True             |
| can_write_tasks           | True             |
| can_create_tasks          | True             |
| can_delete_tasks          | True             |
| can_import_tasks          | True             |
| can_export_tasks          | True             |
| can_read_chats            | True             |
| can_write_chats           | True             |
| can_create_chats          | True             |
| can_delete_chats          | True             |
| can_import_chats          | True             |
| can_export_chats          | True             |
| can_read_assets           | True             |
| can_write_assets          | True             |
| can_create_assets         | True             |
| can_delete_assets         | True             |
| can_import_assets         | True             |
| can_export_assets         | True             |
| can_read_timing_sheets    | True             |
| can_write_timing_sheets   | True             |
| can_create_timing_sheets  | True             |
| can_delete_timing_sheets  | True             |
| can_import_timing_sheets  | True             |
| can_export_timing_sheets  | True             |
+---------------------------+------------------+
